function init(self)
    --local res = androidnative.dostuff()
    local res = androidnative.getraw()
    --print(res)
    gui.set_text(gui.get_node("text1"), "Android says: \n" .. tostring(res))
    
    msg.post(".", "acquire_input_focus")
end

function final(self)
    -- Add finalization code here
    -- Remove this function if not needed
end

function update(self, dt)
    -- Add update code here
    -- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
    -- Add message-handling code here
    -- Remove this function if not needed
end

function on_input(self, action_id, action)
    if (action_id == hash("touch") and action.released) then
        androidnative.vibrate()
    end
end

function on_reload(self)
    -- Add input-handling code here
    -- Remove this function if not needed
end
