function init(self)
    
    msg.post(".", "acquire_input_focus")
    
    local prevcrash = crash.load_previous()
    if prevcrash then
	    local backtrace = crash.get_backtrace(prevcrash)
	    pprint(backtrace)
	    print("Extra data: \n" .. crash.get_extra_data(prevcrash))
    end
    

end

function on_input(self, action_id, action)
    if (action_id == hash("touch") and action.released) then
        msg.post("#sprite", "play_animation", {id = hash("anim")})
    end
end